use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    models: "Modellen",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Instellingen",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    notifications: "Notifications",
    notify_session_reset: "Notify on 5h reset",
    notify_weekly_reset: "Notify on 7d reset",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    token_expired_title: "Claude Code-authenticatiefout",
    token_expired_body: "Voer 'claude' uit in een terminal, gebruik daarna '/login' en volg de stappen. Ververs of herstart de app daarna.",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    antigravity_token_expired_title: "Antigravity-authenticatiefout",
    antigravity_token_expired_body: "Open Antigravity en meld je opnieuw aan. Ververs of herstart de app daarna.",
    codex_window_title: "Codex-gebruiksmonitor",
    antigravity_window_title: "Antigravity-gebruiksmonitor",
    second_suffix: "s",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
