use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    models: "Models",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    notifications: "Notifications",
    notify_session_reset: "Notify on 5h reset",
    notify_weekly_reset: "Notify on 7d reset",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
