use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Aktualisieren",
    refresh_now: "Jetzt",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    models: "Modelle",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Einstellungen",
    start_with_windows: "Mit Windows starten",
    reset_widget_position: "Widgetposition zurücksetzen",
    reset_floating_position: "Position des schwebenden Fensters zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Widget",
    show_floating_monitor: "Schwebendes Fenster",
    lock_floating_position: "Position des schwebenden Fensters sperren",
    detailed_tray_icons: "Symbole",
    notifications: "Notifications",
    notify_session_reset: "Bei Rücksetzung kurzer Limits benachrichtigen",
    notify_weekly_reset: "Bei Rücksetzung langer Limits benachrichtigen",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Limit",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Authentifizierungsfehler",
    token_expired_body: "Führen Sie 'claude' in einem Terminal aus, verwenden Sie dann '/login' und folgen Sie den Anweisungen. Aktualisieren oder starten Sie diese App anschließend neu.",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Melden Sie sich in Codex Desktop an, oder führen Sie 'codex' in einem Terminal aus. Aktualisieren Sie diese App anschließend.",
    antigravity_token_expired_title: "Antigravity-Authentifizierungsfehler",
    antigravity_token_expired_body: "Offnen Sie Antigravity und melden Sie sich erneut an. Aktualisieren oder starten Sie diese App anschliessend neu.",
    codex_window_title: "Codex-Nutzungsmonitor",
    antigravity_window_title: "Antigravity-Nutzungsmonitor",
    second_suffix: "s",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
