use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "更新",
    refresh_now: "今すぐ",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    models: "モデル",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "Windows と同時に開始",
    reset_widget_position: "ウィジェットの位置をリセット",
    reset_floating_position: "フローティングウィンドウの位置をリセット",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェット",
    show_floating_monitor: "フローティングウィンドウ",
    detailed_tray_icons: "アイコン",
    notifications: "Notifications",
    notify_session_reset: "短期枠のリセットを通知",
    notify_weekly_reset: "長期枠のリセットを通知",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "上限",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "Codex Desktop でサインインするか、ターミナルで 'codex' を実行して案内に従ってください。その後、このアプリを更新してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "Every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_badge_near_limit: "Near limit",
    detail_badge_normal: "Normal",
    detail_badge_unused: "Unused",
    detail_badge_cached: "Cached",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
