use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "새로고침",
    refresh_now: "지금",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    models: "모델",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_widget_position: "위젯 위치 초기화",
    reset_floating_position: "플로팅 창 위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯",
    show_floating_monitor: "플로팅 창",
    lock_floating_position: "플로팅 창 위치 잠금",
    detailed_tray_icons: "아이콘",
    notifications: "Notifications",
    notify_session_reset: "단기 한도 초기화 알림",
    notify_weekly_reset: "장기 한도 초기화 알림",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5시간",
    weekly_window: "7일",
    quota_window: "한도",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "Codex Desktop에서 로그인하거나 터미널에서 'codex'를 실행해 안내를 따르세요. 그런 다음 이 앱을 새로 고치세요.",
    antigravity_token_expired_title: "Antigravity 인증 오류",
    antigravity_token_expired_body: "Antigravity를 열고 다시 로그인하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_window_title: "Codex 사용량 모니터",
    antigravity_window_title: "Antigravity 사용량 모니터",
    second_suffix: "초",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
