use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configurações",
    start_with_windows: "Iniciar com o Windows",
    reset_position: "Redefinir Posição",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    notifications: "Notifications",
    notify_session_reset: "Notify on 5h reset",
    notify_weekly_reset: "Notify on 7d reset",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    token_expired_title: "Erro de Autenticação do Claude Code",
    token_expired_body: "Execute 'claude' em um terminal, use '/login' e siga as instruções. Depois disso, atualize ou reinicie este aplicativo.",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    antigravity_token_expired_title: "Erro de Autenticação do Antigravity",
    antigravity_token_expired_body: "Abra o Antigravity e entre novamente. Depois disso, atualize ou reinicie este aplicativo.",
    codex_window_title: "Monitor de uso do Codex",
    antigravity_window_title: "Monitor de uso do Antigravity",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
