use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "Обновить",
    refresh_now: "Сейчас",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    models: "Модели",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    start_with_windows: "Запускать вместе с Windows",
    reset_widget_position: "Сбросить положение виджета",
    reset_floating_position: "Сбросить положение плавающего окна",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Виджет",
    show_floating_monitor: "Плавающее окно",
    lock_floating_position: "Закрепить плавающее окно",
    detailed_tray_icons: "Значки",
    notifications: "Notifications",
    notify_session_reset: "Уведомлять о сбросе краткого лимита",
    notify_weekly_reset: "Уведомлять о сбросе долгого лимита",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5ч",
    weekly_window: "7д",
    quota_window: "Лимит",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Войдите в Codex Desktop или запустите 'codex' в терминале и следуйте инструкциям. Затем обновите это приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
    detail_waiting: "Waiting for usage data",
    detail_auth_required: "Sign in required",
    detail_sign_in_hint: "Resumes after you sign in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "every {interval}",
    detail_rate_limited: "Rate limited - showing cached data",
    detail_badge_rate_limited: "Rate limited",
    detail_badge_error: "Request failed",
    detail_badge_loading: "Loading",
    detail_stale: "Data from last run",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
