use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "AI Usage Monitor",
    refresh: "刷新",
    update_frequency: "刷新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    models: "模型",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "设置",
    start_with_windows: "开机启动",
    reset_position: "重置位置",
    language: "语言",
    system_default: "跟随系统",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "更新检查已在进行中。",
    up_to_date: "当前已是最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新到",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否现在更新？",
    exit: "退出",
    show_widget: "显示小组件",
    notifications: "通知",
    notify_session_reset: "5h 重置时通知",
    notify_weekly_reset: "7d 重置时通知",
    reset_notification_title: "用量窗口已重置",
    reset_notification_body: "{provider} 的 {window} 配额窗口已重置。",
    session_window: "5h",
    weekly_window: "7d",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "小时",
    minute_suffix: "分钟",
    second_suffix: "秒",
    token_expired_title: "Claude Code 认证错误",
    token_expired_body:
        "请在终端运行 'claude'，使用 '/login' 并按提示登录。完成后刷新或重启本应用。",
    codex_token_expired_title: "Codex 认证错误",
    codex_token_expired_body: "请在终端运行 'codex' 并按提示登录。完成后刷新或重启本应用。",
    antigravity_token_expired_title: "Antigravity 认证错误",
    antigravity_token_expired_body: "请打开 Antigravity 并重新登录。完成后刷新或重启本应用。",
    codex_window_title: "Codex 用量监控",
    antigravity_window_title: "Antigravity 用量监控",
    detail_waiting: "等待用量数据",
    detail_auth_required: "需要登录",
    detail_sign_in_hint: "登录后自动恢复",
    detail_reset_unavailable: "重置时间未知",
    detail_resets_in: "{duration}后重置",
    detail_resets_now: "即将重置",
    detail_updated_ago: "{ago}前更新",
    detail_next_in: "{next}后刷新",
    detail_poll_every: "每 {interval}",
    detail_rate_limited: "已限流，显示缓存数据",
    detail_badge_rate_limited: "已限流",
    detail_badge_error: "请求失败",
    detail_badge_loading: "加载中",
    detail_stale: "数据来自上次运行",
    weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
};
