use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "透過 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Gengchou",
    refresh: "重新整理",
    refresh_now: "立即",
    one_minute: "1 分鐘",
    two_minutes: "2 分鐘",
    five_minutes: "5 分鐘",
    ten_minutes: "10 分鐘",
    fifteen_minutes: "15 分鐘",
    thirty_minutes: "30 分鐘",
    models: "模型",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "開機時啟動",
    reset_widget_position: "重設小工具位置",
    reset_floating_position: "重設浮窗位置",
    language: "語言",
    system_default: "系統預設",
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "小工具",
    show_floating_monitor: "浮窗",
    detailed_tray_icons: "圖示",
    notifications: "Notifications",
    notify_session_reset: "短期額度重置時通知",
    notify_weekly_reset: "長期額度重置時通知",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "額度",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    token_expired_title: "驗證錯誤",
    token_expired_body: "請在終端機中執行 'claude'，然後使用 '/login' 並依照提示操作。完成後，請重新整理或重新啟動此應用程式。",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body: "請開啟 Codex Desktop 登入，或在終端機中執行 'codex' 並依照提示操作。完成後請重新整理此應用程式。",
    antigravity_token_expired_title: "Antigravity 驗證錯誤",
    antigravity_token_expired_body: "請開啟 Antigravity 並重新登入。完成後，請重新整理或重新啟動此應用程式。",
    codex_window_title: "Codex 使用量監控",
    antigravity_window_title: "Antigravity 使用量監控",
    second_suffix: "秒",
    detail_waiting: "等待使用量資料",
    detail_auth_required: "需要登入",
    detail_sign_in_hint: "登入後自動恢復",
    detail_reset_unavailable: "重設時間未知",
    detail_resets_in: "{duration}後重設",
    detail_resets_now: "即將重設",
    detail_updated_ago: "{ago}前更新",
    detail_next_in: "{next}後重新整理",
    detail_poll_every: "每 {interval}",
    detail_rate_limited: "已限流，顯示快取資料",
    detail_badge_rate_limited: "已限流",
    detail_badge_error: "請求失敗",
    detail_badge_loading: "載入中",
    detail_badge_near_limit: "接近上限",
    detail_badge_normal: "正常",
    detail_badge_unused: "未使用",
    detail_badge_cached: "上次資料",
    detail_stale: "資料來自上次執行",
    weekdays: ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],
};
